// AUTH
export const POST_SING_UP = 'POST_SING_UP';
export const POST_SING_UP_SUCCESS = 'POST_SING_UP_SUCCESS';
export const POST_SING_UP_REQUEST = 'POST_SING_UP_REQUEST';
export const POST_SING_UP_FAILURE = 'POST_SING_UP_FAILURE';
export const POST_SING_IN = 'POST_SING_IN';
export const POST_SING_IN_SUCCESS = 'POST_SING_IN_SUCCESS';
export const POST_SING_IN_REQUEST = 'POST_SING_IN_REQUEST';
export const POST_SING_IN_FAILURE = 'POST_SING_IN_FAILURE';
export const POST_CONFIRM = 'POST_CONFIRM';
export const POST_CONFIRM_SUCCESS = 'POST_CONFIRM_SUCCESS';
export const POST_CONFIRM_FAILURE = 'POST_CONFIRM_FAILURE';
export const SING_OUT = 'SING_OUT';
export const TOKEN_NOT_VALID = 'TOKEN_NOT_VALID';

// UPDATE
export const PUT_UPDATE = 'PUT_UPDATE';
export const PUT_UPDATE_SUCCESS = 'PUT_UPDATE_SUCCESS';
export const PUT_UPDATE_REQUEST = 'PUT_UPDATE_REQUEST';
export const PUT_UPDATE_FAILURE = 'PUT_UPDATE_FAILURE';

// MESSAGES
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';
export const UPDATE_MESSAGE_COUNT = 'UPDATE_MESSAGE_COUNT';

// SENDERS
export const GET_SENDERS = 'GET_SENDERS';
export const GET_SENDERS_REQUEST = 'GET_SENDERS_REQUEST';
export const GET_SENDERS_SUCCESS = 'GET_SENDERS_SUCCESS';
export const GET_SENDERS_FAILURE = 'GET_SENDERS_FAILURE';

// CLEAR
export const CLEAR_ERROR = 'CLEAR_ERROR';

// WEBSOCKET
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN';
export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE';
export const WEBSOCKET_SEND = 'WEBSOCKET_SEND';

// NETWORK
export const NETWORK_FAILURE = 'NETWORK_FAILURE';

//USER
export const PUT_EDIT_PROFILE = 'PUT_EDIT_PROFILE';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const PUT_EDIT_PROFILE_SUCCESS = 'PUT_EDIT_PROFILE_SUCCESS';
export const GET_PROFILE_DATA_REQUEST = 'GET_PROFILE_DATA_REQUEST';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE = 'GET_PROFILE_DATA_FAILURE';
export const PUT_CHANGE_PASSWORD = 'PUT_CHANGE_PASSWORD';
export const GET_USER_CONTRACTS = 'GET_USER_CONTRACTS';
export const GET_USER_CONTRACTS_SUCCESS = 'GET_USER_CONTRACTS_SUCCESS';
export const GET_USER_CONTRACTS_REQUEST = 'GET_USER_CONTRACTS_REQUEST';
export const ADD_USER_CONTRACT = 'ADD_USER_CONTRACT';
export const ADD_USER_CONTRACT_REQUEST = 'ADD_USER_CONTRACT_REQUEST';
export const ADD_USER_CONTRACT_SUCCESS = 'ADD_USER_CONTRACT_SUCCESS';